### PR TITLE
Feature/i 14 categorize students

### PR DESCRIPTION
**Pull request by dillam**
`spreadsheet.py` takes data from the spreadsheet created by [this](https://goo.gl/forms/GHhgcRSyP2WU0HUF2) google form and inputs the data into `data.csv` in the following format.
```
"eltmanm","True","True","True"
"dillam","True","False","False"
```

### CODE REVIEW

**Comment by yeeunmariakim** [comment]
@dillam are there any security issues related to any of the information stored in `client_secret.json`?

**Comment by dillam** [comment]
@eltmanm can you answer that since you worked on it?

**Comment by eltmanm** [comment]
the `client_secret.json` file is just there to allow access to the spreadsheet from the program, it doesn't depend on who opens it, thankfully. it and the spreadsheet it's pulling from have had information exchanged to link them. the line that says `gatorgrouperinputkey@gatorgrouper.iam.gserviceaccount.com` was generated in the json file and also has shared edit and viewing access to the spreadsheet.
The user will have to copy this into the sharing for any other class's spreadsheet in order to use it for that class. The setup is a little bit confusing and we'll need it described in documentation, so ill need to help whoever's doing that so I can share the information I acquired.

**Comment by eltmanm** [comment]
cool. what group do I need to give to once I have initial usage documentation written up?

**Comment by yeeunmariakim** [comment]
@eltmanm that information should be in the issue tracker.

**Pull request merged**
