### PR TITLE
Feature/fixing travis

### PR DESCRIPTION
**Pull request by Andre-Bryan**
Should work fixed the error. it had an error currently because the file was seeing the display_student_groups but that is not present in master so everything should work

### CODE REVIEW

**Comment by yeeunmariakim** [comment]
@Andre-Bryan can you pull from master to demonstrate that this fix will fix the Travis build in master?

**Comment by Andre-Bryan** [comment]
passed

**Comment by Andre-Bryan** [comment]
it passed
0 errors

**Comment by Andre-Bryan** [comment]
need to try some other things because coveralls did not get anything like it was supposed to

**Pull request merged**
